print("Hello from Feature A!")
print("Hello from Feature B!")
print("Testing commit -a shortcut directly")
print("Learning commit amend")
print("Hello from GitHub remote!")
print("Testing rebase workflow locally")